# Masks the stock provision.conf, whose /root entries clash with the ostree
# /root -> /var/roothome symlink.

f^ /etc/motd.d/50-provision.conf - - - - login.motd
f^ /etc/issue.d/50-provision.conf - - - - login.issue

f^ /etc/hosts - - - - network.hosts

f^ /var/roothome/.ssh/authorized_keys 600 root root - ssh.authorized_keys.root
