# Masks the stock systemd-resolve.conf, changing L! to L+ to force the symlink at
# every boot. The build bind-mounts /etc/resolv.conf, leaving a stub that L! skips.
# https://github.com/bootc-dev/bootc/issues/1064
L+ /etc/resolv.conf - - - - ../run/systemd/resolve/stub-resolv.conf
