#!/bin/sh
cat <<'BANNER'

Ubuntu bootc live session.

Install this system to a disk, wiping it, with:

    bootc-ubuntu-install DEVICE

Disks on this machine:

BANNER
lsblk --nodeps --paths --exclude 7,11 --output NAME,SIZE,MODEL
echo
